# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Volvo test execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        working-directory: testautomation
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: npm clean install
      run: npm uninstall fibers && rm package-lock.json && rm -R node_modules && npm install
    - name: Start selenium docker grid set up
      run:  docker-compose -f "docker-compose.yml" up -d --build
    - name: sleep for 10 seconds
      uses: whatnick/wait-action@master
      with:
       time: "10s"
    - name: Run webdriverIO scripts on Selenium grid
      run: npm run test-docker
    - name: Publish allure report
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: testautomation/allure-report
